create table if not exists public.consultation_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null,
  phone text not null,
  business_name text not null,
  business_number text not null,
  email text,
  industry text not null,
  annual_revenue text not null,
  needed_fund text not null,
  existing_loan text not null,
  overdue_tax text not null,
  interest text not null,
  message text,
  privacy_agreed boolean not null default false,
  source text,
  user_agent text
);

comment on table public.consultation_requests is 'MABASA homepage consultation requests. Access only through the serverless API.';

alter table public.consultation_requests enable row level security;

revoke all on public.consultation_requests from anon;
revoke all on public.consultation_requests from authenticated;
revoke all on sequence public.consultation_requests_id_seq from anon;
revoke all on sequence public.consultation_requests_id_seq from authenticated;

drop policy if exists "No public read access" on public.consultation_requests;
drop policy if exists "No public insert access" on public.consultation_requests;
drop policy if exists "No public update access" on public.consultation_requests;
drop policy if exists "No public delete access" on public.consultation_requests;

create policy "No public read access"
on public.consultation_requests
for select
using (false);

create policy "No public insert access"
on public.consultation_requests
for insert
with check (false);

create policy "No public update access"
on public.consultation_requests
for update
using (false)
with check (false);

create policy "No public delete access"
on public.consultation_requests
for delete
using (false);

create table if not exists public.consultation_rate_limits (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  ip_hash text not null,
  source text
);

comment on table public.consultation_rate_limits is 'Hashed rate-limit records for MABASA homepage consultation requests.';

create index if not exists consultation_rate_limits_ip_hash_created_at_idx
on public.consultation_rate_limits (ip_hash, created_at desc);

alter table public.consultation_rate_limits enable row level security;

revoke all on public.consultation_rate_limits from anon;
revoke all on public.consultation_rate_limits from authenticated;
revoke all on sequence public.consultation_rate_limits_id_seq from anon;
revoke all on sequence public.consultation_rate_limits_id_seq from authenticated;

drop policy if exists "No public rate limit read access" on public.consultation_rate_limits;
drop policy if exists "No public rate limit insert access" on public.consultation_rate_limits;
drop policy if exists "No public rate limit update access" on public.consultation_rate_limits;
drop policy if exists "No public rate limit delete access" on public.consultation_rate_limits;

create policy "No public rate limit read access"
on public.consultation_rate_limits
for select
using (false);

create policy "No public rate limit insert access"
on public.consultation_rate_limits
for insert
with check (false);

create policy "No public rate limit update access"
on public.consultation_rate_limits
for update
using (false)
with check (false);

create policy "No public rate limit delete access"
on public.consultation_rate_limits
for delete
using (false);
